included:
  - LoginFacebook
  - Pods
excluded: 
  - Pods
  - Pods/Products
disabled_rules:
  - variable_name
  - trailing_whitespace
  - force_cast
type_body_length:
  - 300 # warning
  - 400 # error
function_body_length:
  - 200
